 stage('GENERATE K0s Deployment YAML') {
            steps {
                script {
                    def deploymentYamlContent = """
                                     apiVersion: apps/v1
                                     kind: Deployment
                                     metadata:
                                         name: checkout-service
                                     spec:
                                         replicas: 1
                                         selector:
                                             matchLabels:
                                                 app: checkout-service
                                         template:
                                             metadata:
                                                 labels:
                                                     app: checkout-service
                                             spec:
                                                 containers:
                                                     - name: checkout-service
                                                       image: ${NEXUS_DOCKER_REPO}/checkout-service:c1
                                                       ports:
                                                           - containerPort: 8088
                                    """
                    writeFile file: 'k0s-deployment.yaml', text: deploymentYamlContent
                }
            }
        }
